### ISSUE TITLE
 README.md 수정 

### ISSUE THREAD

**Issue by krung2** [Hong-JunHyeok/react18-boilerplate#9]
현재 `npm`에서 `install`한 후 `setting`하는 과정
```shell
# Install Package
npm i create-react18-boilerplate
```
에서

```shell
# Create App
mkdir [project_name]
cd [project_name]
create-react18-boilerplate # Create a project when entering a command
```
해당 방법으로 `script`를 사용하기 위해서는
```shell
npm i -g create-react18-boilerplate
```
형태의 `global`로 바꾸는 것이 좋아 보입니다
+ `boiler plate`라는 점에서도 `global`로 설치가 더욱 적합하지 않을까요?

**Comment by krung2** [comment]
`yarn`예시도 만들어주세요!

**Comment by krung2** [comment]
바쁘면 제가 Fork따서 올리겠습니다...

**Comment by Hong-JunHyeok** [comment]
@krung2 https://github.com/Hong-JunHyeok/create-react18-boilerplate/commit/730bb12f8a91b79731e7c6725852b743a5b3e361 에서 수정하였습니다.
